# -*- coding: utf-8 -*-
"""Cópia de ProjetoIndividualM3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12nXjqL8c7omgbc_NpM2JijCvDSzVJfyI

#1. Importando as Bibliotecas Necessárias
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display, Markdown

"""#2. Carregando os Dados"""

dados = {
    'Dia': ['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado', 'Domingo'],
    'Horas Trabalhadas': [6, 7, 8, 6, 7, 5, 4],
    'Bugs Corrigidos': [3, 2, 1, 4, 3, 2, 1],
    'Tarefas Concluídas': [5, 4, 6, 4, 5, 3, 2]
}

df = pd.DataFrame(dados)

"""# 4. Calculo dos Indicadores"""

#Total de Horas Trabalhadas
total_horas = df['Horas Trabalhadas'].sum()
#Total de Bugs Corrigidos
total_bugs = df['Bugs Corrigidos'].sum()
#Total de Tarefas Concluídas
total_tarefas = df['Tarefas Concluídas'].sum()

#Média de Horas Trabalhadas
media_horas = df['Horas Trabalhadas'].mean()
#Méda de Bugs Corrigidos
media_bugs = df['Bugs Corrigidos'].mean()
#Média de Tarefas Concluídas
media_tarefas = df['Tarefas Concluídas'].mean()

#Produtividade Diária (Tarefas concluídas por hora)
df['Produtividade'] = total_tarefas / total_horas

"""#5. Gráfico"""

display(Markdown(f"**Total de Horas Trabalhadas:** {total_horas}"))
display(Markdown(f"**Média Diária de Horas Trabalhadas:** {media_horas:.2f}"))
display(Markdown(f"**Total de Bugs Corrigidos:** {total_bugs}"))
display(Markdown(f"**Média Diária de Bugs Corrigidos:** {media_bugs:.2f}"))
display(Markdown(f"**Total de Tarefas Concluídas:** {total_tarefas}"))
display(Markdown(f"**Média Diária de Tarefas Concluídas:** {total_tarefas / total_horas}"))

display(df)

# @title Tarefas Concluídas

from matplotlib import pyplot as plt
df['Tarefas Concluídas'].plot(kind='hist', bins=20, title='Tarefas Concluídas')
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title Bugs Corrigidos

from matplotlib import pyplot as plt
df['Bugs Corrigidos'].plot(kind='hist', bins=20, title='Bugs Corrigidos')
plt.gca().spines[['top', 'right',]].set_visible(False)

# @title Horas Trabalhadas

from matplotlib import pyplot as plt
df['Horas Trabalhadas'].plot(kind='hist', bins=20, title='Horas Trabalhadas')
plt.gca().spines[['top', 'right',]].set_visible(False)